// Single source of truth for Tauri command names.
// Keep this in sync with docs/TAURI_COMMANDS.md and src-tauri/src/lib.rs.
// No raw command string should appear anywhere else in src/.

export const TAURI_COMMANDS = {
  system: {
    checkBinaries: "check_binaries",
    debugPaths: "debug_paths",
    debugInstallation: "debug_installation",
    startAllServices: "start_all_services",
    stopAllServices: "stop_all_services",
    testApacheConfig: "test_apache_config",
    testMysqlConfig: "test_mysql_config",
    createDirectoryStructure: "create_directory_structure",
    getAutostart: "get_autostart",
    setAutostart: "set_autostart",
    getSystemInfo: "get_system_info",
  },
  services: {
    getApacheStatus: "get_apache_status",
    getMysqlStatus: "get_mysql_status",
    getPhpStatus: "get_php_status",
    startMysql: "start_mysql",
    stopMysql: "stop_mysql",
    startApache: "start_apache",
    stopApache: "stop_apache",
    toggleApache: "toggle_apache",
    toggleMysql: "toggle_mysql",
    togglePhp: "toggle_php",
    getServiceLogs: "get_service_logs",
    logCrashEvent: "log_crash_event",
    backupMysqlDatabase: "backup_mysql_database",
    backupMysqlDatabaseNamed: "backup_mysql_database_named",
    listMysqlDatabases: "list_mysql_databases",
    listMysqlDatabasesDetailed: "list_mysql_databases_detailed",
    restoreMysqlDatabase: "restore_mysql_database",
    listMysqlUsers: "list_mysql_users",
    createMysqlUser: "create_mysql_user",
    dropMysqlUser: "drop_mysql_user",
    setMysqlUserPassword: "set_mysql_user_password",
    openPhpTerminal: "open_php_terminal",
  },
  php: {
    getVersions: "get_php_versions",
    switchVersion: "switch_php_version",
    downloadVersion: "download_php_version",
    listExtensions: "list_php_extensions",
    toggleExtension: "toggle_php_extension",
  },
  config: {
    read: "read_config",
    update: "update_config",
    backup: "backup_config",
    listBackups: "list_config_backups",
    restoreBackup: "restore_config_backup",
  },
  tray: {
    showMainWindow: "show_main_window",
    hideToTray: "hide_to_tray",
    quitApp: "quit_app",
    setTooltip: "set_tray_tooltip",
    refreshMenu: "refresh_tray_menu",
  },
  terminal: {
    spawn: "spawn_terminal",
    sendInput: "send_terminal_input",
    kill: "kill_terminal_session",
  },
  security: {
    analyze: "analyze_security",
  },
  ssl: {
    getStatus: "get_ssl_status",
    generateCert: "generate_ssl_cert",
    enable: "enable_ssl",
    disable: "disable_ssl",
  },
  vhosts: {
    list: "list_vhosts",
    add: "add_vhost",
    remove: "remove_vhost",
    toggle: "toggle_vhost",
    getHostsEntries: "get_hosts_entries",
    updateHostsEntry: "update_hosts_entry",
  },
  backup: {
    createFull: "create_full_backup",
    listFull: "list_full_backups",
    restoreFull: "restore_full_backup",
    deleteFull: "delete_full_backup",
    openFolder: "open_backups_folder",
  },
} as const;
